# Generated by Django 3.2.8 on 2023-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=30)),
                ('temporada', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='CLP', max_length=10)),
            ],
        ),
    ]
