# Generated by Django 3.2.8 on 2023-06-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botania', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='AA123')),
                ('nombre', models.CharField(max_length=50, verbose_name='Amapola')),
                ('tamaño', models.CharField(max_length=30, verbose_name='Mediano')),
                ('temporada', models.CharField(max_length=30, verbose_name='Primavera')),
                ('color', models.CharField(max_length=30, verbose_name='Rojo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='5990')),
                ('moneda', models.CharField(default='CLP', max_length=10, verbose_name='CLP')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
