# Generated by Django 3.2.8 on 2023-06-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botania', '0003_auto_20230630_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='moneda',
            field=models.CharField(default='CLP', max_length=10),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='tamaño',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='temporada',
            field=models.CharField(max_length=30),
        ),
    ]
