# Generated by Django 3.2.8 on 2023-06-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botania', '0004_auto_20230630_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
